# -*- coding: utf-8 -*-
"""SMOTENN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdkCecLL8WtHINK2LdrFeITCS_gS6QhH
"""

from imblearn.combine import SMOTEENN
import pandas as pd
import os

# Define the directory where your processed denoised labeled files are stored
input_dir = '/content/drive/My Drive/ecg_classification_master/denoised_labeled'

# Directory for the balanced dataset output
output_dir = '/content/drive/My Drive/ecg_classification_master/smoteenn_label'

# Ensure the output directory exists
os.makedirs(output_dir, exist_ok=True)

# Initialize an empty list to collect all the data
all_data = []

# Process each file in the input directory
for filename in os.listdir(input_dir):
    if filename.endswith('.csv'):
        file_path = os.path.join(input_dir, filename)
        df = pd.read_csv(file_path, header=None)
        all_data.append(df)

# Combine all files into one DataFrame
combined_df = pd.concat(all_data, ignore_index=True)

# Remove rows with invalid class '-1' (if any)
valid_classes = combined_df.iloc[:, -1] != -1
combined_df = combined_df[valid_classes]