# -*- coding: utf-8 -*-
"""TOMEKS+SMOTE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdkCecLL8WtHINK2LdrFeITCS_gS6QhH
"""

from imblearn.combine import SMOTETomek
import pandas as pd
import os

# Define input/output directories
input_dir = '/content/drive/My Drive/ecg_classification_master/denoised_labeled'
output_dir = '/content/drive/My Drive/ecg_classification_master/tomek_smote_label'
os.makedirs(output_dir, exist_ok=True)

# Load all labeled data
all_data = []
for filename in os.listdir(input_dir):
    if filename.endswith('.csv'):
        file_path = os.path.join(input_dir, filename)
        df = pd.read_csv(file_path, header=None)
        all_data.append(df)
combined_df = pd.concat(all_data, ignore_index=True)

# Remove rows with invalid class '-1'
valid_classes = combined_df.iloc[:, -1] != -1
combined_df = combined_df[valid_classes]

# Separate features and labels
features = combined_df.iloc[:, :-1]
labels = combined_df.iloc[:, -1]

# Apply SMOTE + Tomek Links
smotetomek = SMOTETomek(random_state=42)
X_resampled, y_resampled = smotetomek.fit_resample(features, labels)

# Save the balanced dataset
resampled_dataset = pd.DataFrame(X_resampled)
resampled_dataset['Label'] = y_resampled
resampled_file_path = os.path.join(output_dir, 'balanced_dataset_smotetomek.csv')
resampled_dataset.to_csv(resampled_file_path, header=False, index=False)

print("Balanced dataset using SMOTE + Tomek Links created and saved!")
print("Class distribution in the resampled dataset:")
print(resampled_dataset['Label'].value_counts())