# -*- coding: utf-8 -*-
"""SMOTE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdkCecLL8WtHINK2LdrFeITCS_gS6QhH
"""

from imblearn.over_sampling import SMOTE
import pandas as pd
import os

# Define the directory where your processed denoised labeled files are stored
input_dir = '/content/drive/My Drive/ecg_classification_master/denoised_labeled'

# Directory for the balanced dataset output
output_dir = '/content/drive/My Drive/ecg_classification_master/balanced_label'

# Ensure the output directory exists
os.makedirs(output_dir, exist_ok=True)

# Initialize an empty list to collect all the data
all_data = []

# Process each file in the denoised_labeled directory
for filename in os.listdir(input_dir):
    if filename.endswith('.csv'):
        file_path = os.path.join(input_dir, filename)
        df = pd.read_csv(file_path, header=None)
        all_data.append(df)

# Combine all files into one DataFrame
combined_df = pd.concat(all_data, ignore_index=True)

# Separate features and labels
features = combined_df.iloc[:, :-1]  # Features are all columns except the last one
labels = combined_df.iloc[:, -1]     # Labels are the last column

# Remove rows with invalid class '-1' (if necessary)
valid_classes = labels != -1
combined_df = combined_df[valid_classes]

# Separate features and labels again after filtering out '-1'
features = combined_df.iloc[:, :-1]
labels = combined_df.iloc[:, -1]

# Initialize SMOTE
smote = SMOTE(sampling_strategy='auto', random_state=42)

# Apply SMOTE to resample the dataset
X_resampled, y_resampled = smote.fit_resample(features, labels)

# Combine the resampled features and labels into a new DataFrame
resampled_dataset = pd.DataFrame(X_resampled)
resampled_dataset['Label'] = y_resampled  # Add the label column

# Save the resampled dataset to a new CSV
resampled_file_path = os.path.join(output_dir, 'balanced_dataset_smote.csv')
resampled_dataset.to_csv(resampled_file_path, header=False, index=False)

print("Balanced dataset using SMOTE created and saved!")

# Print the distribution of classes in the resampled dataset
print(f"Class distribution in the resampled dataset:")
print(resampled_dataset['Label'].value_counts())