# -*- coding: utf-8 -*-
"""Resize Image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdkCecLL8WtHINK2LdrFeITCS_gS6QhH
"""

import os
import cv2
from tqdm import tqdm

input_base_dir = '/content/drive/My Drive/ecg_classification_master/tomeksmote_scallograms'
output_base_dir = '/content/drive/My Drive/ecg_classification_master/tomeksmote_resize_image'
target_size = (224, 224)

def preprocess_and_save_images(input_dir, output_dir, target_size=(224, 224)):
    os.makedirs(output_dir, exist_ok=True)
    for filename in tqdm(os.listdir(input_dir), desc=f"Processing class {os.path.basename(input_dir)}"):
        if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
            file_path = os.path.join(input_dir, filename)
            image = cv2.imread(file_path)
            if image is None:
                continue
            # Crop bottom half if needed (optional, comment out if not needed)
            # h, w, _ = image.shape
            # image = image[int(h/2):, :]
            resized_image = cv2.resize(image, target_size)
            cv2.imwrite(os.path.join(output_dir, filename), resized_image)

# Loop over class folders (0 to 4)
for label in range(5):
    input_dir = os.path.join(input_base_dir, str(label))
    output_dir = os.path.join(output_base_dir, str(label))
    preprocess_and_save_images(input_dir, output_dir)

print("✅ All class images have been processed and resized.")