# -*- coding: utf-8 -*-
"""Signal to Scalogram

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdkCecLL8WtHINK2LdrFeITCS_gS6QhH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pywt
import os

# Set paths
file_path = '/content/drive/My Drive/ecg_classification_master/tomeksmote_balanced_label/balanced_dataset_smote.csv'
output_dir_base = '/content/drive/My Drive/ecg_classification_master/tomeksmote_scallograms'

# Load data
data_df = pd.read_csv(file_path, header=None)
segments = data_df.iloc[:, :-1].values
labels = data_df.iloc[:, -1].values
segment_size = 1000

# Make output folders for each class label
for label in np.unique(labels):
    if label != -1:
        os.makedirs(os.path.join(output_dir_base, str(label)), exist_ok=True)

# For each segment, generate and save the scalogram
for i, (segment, label) in enumerate(zip(segments, labels)):
    if label == -1:
        continue
    scales = np.arange(1, 64)
    cwt_coeffs, _ = pywt.cwt(segment, scales, 'morl')

    plt.figure(figsize=(8, 4))
    plt.imshow(np.abs(cwt_coeffs), extent=[0, segment_size, 1, 64], cmap='jet', aspect='auto')
    plt.axis('off')
    output_path = os.path.join(output_dir_base, str(int(label)), f'scalogram_{i+1}.png')
    plt.savefig(output_path, bbox_inches='tight', pad_inches=0)
    plt.close()